name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       name: Checkout
   uses: actions/checkout@v4

  name: Install dependencies
 run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip \
            autoconf libtool pkg-config zlib1g-dev \
            libncurses5-dev libncursesw5-dev cmake \
            libffi-dev libssl-dev automake

      name: Install Buildozer run: |
          python3 -m pip install --user --upgrade buildozer cython

      name: Build APK    run: |
          export PATH="$HOME/.local/bin:$PATH"
          buildozer -v android debug

     name: Upload APK
   uses: actions/upload-artifact@v4
   with:
          name: Snake-Game-APK
          path: bin/*.apk
